spring.output.ansi.enabled: detect
logging:
  pattern.console: "%highlight(%.-1level) %date{HH:mm:ss.SSS} [%30.30logger] %msg%n"
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.test: WARN
    com.tsi.dv: DEBUG